### ISSUE TITLE
clussiana@psi.org on build #11: When I Sselect Extra large as a Font size, the Plan module…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#110]
Feedback from clussiana@psi.org : When I Sselect Extra large as a Font size, the Plan module disappears and the only to have it back is by uninstalling the app and insralling it again.

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=573c036a5c3f1401000ccbd7&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/5734aab7ed3829010035e991/d61b6167-1f28-4899-b2b7-b2a0ee909331.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>17% Unplugged</td></tr><tr><td>Memory free</td><td>255 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
Not able to replicate it on a tablet, trying on a phone

**Comment by ifoche** [comment]
I've been able to replicate in a phone the fact that you cannot see the planning tab when extra-large font is selected, but at least, I can click on settings again and put font setting back to another font size. In my opinion, if the user can select a different font size this is not a bug (the user can still avoid extra large font or use default setting). Can you confirm that you're able to change the font setting back again?

**Comment by cristinaelle** [comment]
The issue is not that I can't change the font size back to a smaller one. The issue is that when I select extra large as a font size, the Plan module disappears and I can't get the Plan module back even if I select a smaller font size. The only way to get the Plan module back is to uninstall and reinstall the app.

Please, note that the screenshot is not relevant in this case (tell me if you want me to send you the right screenshot. This is what I tried to send you from TZ and didn't get through because of poor internet connectivity. Now, I want to avoid to select Extra large again and have the Plan module disappear and uninstall and reinstall everything again. But if you need the right screenshot, I will do this).

**Comment by rodmelia** [comment]
One option is to remove extra large as an option

**Comment by ifoche** [comment]
@cristinaelle yes, I think that it would be helpful to have a couple of screenshots to see exactly what you're seeing, because in my case both in tablet and 4.5 inches phone, I have not been able to replicate it. Can you tell me in which device are you having this issue? Is this something that you can replicate in a different device? The solution that @rodmelia is suggesting sounds good to me, but I'm a little bit worried about devices we're probably not taking into account where large font may make sense...

**Comment by cristinaelle** [comment]
Samsung Tab 4 - SM-T531

**Comment by rodmelia** [comment]
Ignacio: let's discuss in next review. One option is to remove altogether the Customize font option. Maybe 1.4 ?

**Comment by rodmelia** [comment]
Let's 'hide' the option to change fonts from the app settings. Users can still change font  rom the OS
