### ISSUE TITLE
clussiana@psi.org on build #11: Can't see tge first cool graph in tge Monitor module.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#111]
Feedback from clussiana@psi.org : Can't see tge first cool graph in tge Monitor module.

 [Link to buddybuild feedback from build 11](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=573c686b69755e0100d075da&bnum=11)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/5734aab7ed3829010035e991/bf64ae49-15ad-47e5-8247-0373b42c262e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>11</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>3% Unplugged</td></tr><tr><td>Memory free</td><td>207 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
I'm not able to replicate this, can you send me a mail with the user/pass/server combination where you've seen this effect?

**Comment by cristinaelle** [comment]
hnqis.psi-mis.org demoPSI Temp1234

It works fine on Genymotion; it doesn't work on my tablet. Janet had a similar experience with another user (demoNG Temp1234): it was showing up in Genymotion, at that time it was showing up on my tablet, but it wasn't on hers. 

Graham suggested that it could be because we haven't sent any assessment with that user, but this is not the case: we did send surveys and the first graph doesn't show up.

**Comment by ifoche** [comment]
Confirmed, I'm able to replicate it with the user you provided. Thanks!
