### ISSUE TITLE
Composite Scores: Overall score calculation

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#123]
Feedback from clussiana@psi.org : Sections that have all their questions unanswered still count into the overall QoC score: in this survey the second section has been left blank and its CScore is 0% and this underestimates the overall QoC score of the survey.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/578d303c4b18a0010061010c/739be8fa-83b1-4517-92e6-611430ac4fb6.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>22</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>42% Charging</td></tr><tr><td>Memory free</td><td>523 MB / 1376 MB</td></tr></table>

 [Link to buddybuild feedback from build 22](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=578e6eb266ec1e0100ecef42&bnum=22)

**Comment by cristinaelle** [comment]
@ifoche: when fixing this, please, check that also sub-sections with unanswered questions don't factor into the CScore of the section. i.e. Survey A is composed of Section 1 and Section 2. Section 1 includes Section 1.1 and Section 1.2. Section 1.1 is left blank, Section 1.2 is answered. CScore of Section 1 is == Section 1.2 because Section 1.1 hasn't been answered and shouldn't factor into the CScore of the section 1 level above.
tell me if this makes sense, please!
gracias!

**Comment by cristinaelle** [comment]
@rodmelia: can we find a nice solution for this in the server, too? in theory, we shouldn't see 0 values in case a tab is not taken or in case all the questions of that tab are not answered. 0 values will affect all our scores (composite scores and QoC scores) and will undermine the whole point of this app. 

![screen shot 2016-07-19 at 10 50 12 pm](https://cloud.githubusercontent.com/assets/12784825/16964281/3dcfa5b4-4e03-11e6-9577-3003fdcdeefb.jpg)

**Comment by ifoche** [comment]
Just a question here. Is there a root CS configured in the server? When there's no root CS the overall CS is calculated as the average of all the root CS found. May this be the case?

**Comment by gtrsmith** [comment]
Hi all, 

This is fixed. We were missing a composite indicator. The scores are now functioning as expected (only answered questions are included in the composite score). Cristina, see below. 

We will review all configurations to make sure this is not an issue elsewhere. 

![image](https://cloud.githubusercontent.com/assets/14224713/16968847/50e3de32-4ddf-11e6-813c-8a573c0274f4.png)

**Comment by rodmelia** [comment]
I have moved this to ready because we have determined (after a long email conversation) that the long term fix can only be implemented in HNQIS app:

Current behavior: if the DEs for a composite indicator have null answers (e.g. ALL answers are null), the associated score is calculated as 0. 
Desired behavior: if ALLL DEs for a comp. indicator are ALL null, no score should be submitted, leaving it blank/ null. 

Ignacio: could you please generate a new BB with this modification?

**Comment by adrianq** [comment]
@rodmelia I have been double checking this and it looks like we did this change like 13 days ago. So it should be like this in the latest hnqis bb version I released a few days ago. Are you experienced a different behaviour? Are you testing it with the latest version?

**Comment by josemp10** [comment]
Hi @aquintana, I think it is still sending '0' values with the latest
buddybuild version (24, right?).

I have pushed one survey with only one value. I got the following report

https://hnqis.psi-mis.org/dhis-web-event-reports/index.html?id=n7k8OzBL8CX

The first row represents the comp. scores and the answered question pushed
with the HNQIS version that already is in google play
The second row is using HNQIS buddybuild version 24 (same data entry ->
only one question answered)

In case it helps, the details of my testing:

server: hnqis.psi-mis.org
user: jose_test2
passwd: JGM2015xx
org. unit: test5
program: NG PPMV ICM

**Comment by adrianq** [comment]
@josemp10 I have checked it again with Ina (the developer in charge of this part) and it looks to us it could be a problem regarding the event report.

If you use the API instead of the event report you can see that these are the values for the Google Play version you submitted:
https://hnqis.psi-mis.org/api/events/eWwitdEp0Qd
where composite scores are been submitted with value equal 0.

However if you look at these values for the buddybuild version you submitted:
https://hnqis.psi-mis.org/api/events/BtRlp2cAa9b
The composite scores with value equal 0 are not being submitted.

This [Dhis2 bug](https://bugs.launchpad.net/dhis2/+bug/1600222) opened a few days ago can have something to do with it.

In our opinion composite scores without value are not being submitted in the last  two buddybuild versions and this is actually a problem in the Dhis UI.

CC @rodmelia

**Comment by josemp10** [comment]
God....

I have tested it too and @aquintana you are totally right, it is a problem
in the event report. Sorry for the confusion (I should have checked the API
result first).

Thanks!

**Comment by adrianq** [comment]
Closing this card (it has already been implemented for hnqis and eds). If anybody encounters any problem, just reopen it or create a new one.
