### ISSUE TITLE
Child questions as compulsory when showed

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#132]
Feedback from ekiambi@psi.org : I did not complete all mandatory questions and was still able to upload the assessment for cervical cancer.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/579e7e98a699010100a20373/baf8dbe5-3c8a-4607-aace-39a510f56b8e.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 09 2016 07:09:50 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>24</td></tr><tr><td>Device type</td><td>SM-P555</td></tr><tr><td>Screen size</td><td>768</td></tr><tr><td>Screen size</td><td>768px by 1024px</td></tr><tr><td>Battery</td><td>84% Unplugged</td></tr><tr><td>Memory free</td><td>891 MB / 1890 MB</td></tr></table>

 [Link to buddybuild feedback from build 24](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=57a981be38c00a01003dbd3f&bnum=24)

**Comment by adrianq** [comment]
Currently the application do not allow to send surveys with uncompleted parent mandatory questions. In other words, mandatory questions without parent. The question highlighted in the screenshot ('Applies cryotip to the cervix..') is a child question and therefore it is not compulsory to answer it in order to complete and send the survey. This was the requirement we had by the time compulsory question were implemented.

We can certainly implement this. Compulsory question can be either a parent or child question. Child question will only be actually compulsory if they are displayed (not hidden). @rodmelia do you want us to implement this for the next release?

**Comment by cristinaelle** [comment]
Yes, please, because in some cases we have a first question at the top of the checklist that asks 'Has this service been provided?' and in case of Yes, all the questions open up. This means that for some health services, compulsory questions are child questions, ONLY. To preserve the comparability of quality scores of these health services, we need to implement what you're suggesting (compulsory questions can be either a parent or a child question AND child questions will only be compulsory when displayed).

**Comment by adrianq** [comment]
Understood. Will take care of this.
