### ISSUE TITLE
clussiana@psi.org | HNQIS does NOT work on Android 6

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#158]
Samsung tablet: Model SM-T555 6.0.1 Unable to login 

It works on other tablets:
Samsung tablet: Model SM-T531 5.0.2 App works
HTC Phone: Model HTC One 801e  5.0.2 App works
OPPO Phone: Model 1201 5.1 App works

**Comment by ifoche** [comment]
Did you tested it on other Android 6 device? It's quite strange because we tested Android 6 before creating the release (we introduced the new Credentials system) so I would trend to think that it is not that HNQIS do not work on Android 6, but probably there's something else we're not seeing about your use case. It's probably a bug, but I would probably need more information. I'm now travelling in Myanmar for another project, so sorry because I won't be very responsive this week but I'll take care of it as fast as I can and come back to you with more questions.

**Comment by cristinaelle** [comment]
Yes, tested on Android 6, only one tablet and it didn't work at all. Tried multiple times.

**Comment by rodmelia** [comment]
@cristinaelle : should we buy a T555 and test? Ignacio has tested in virtual devices running 6.0.1 and he is not having problems.

**Comment by cristinaelle** [comment]
Linda tried one more time and this is the result of her test:

"I have uninstalled and re-installed, but it is still not working. 
- I am able to install Build #54 on the tablet
- When i tap, it opens the landing page for the login details
- I am not able to type in any of the log-in details. The back arrow doesn't respond either

The same tablet (Samsung SM-T555 running on Android v6) works perfectly okay with the HNQIS version on play store.

I am wondering whether it is related to bb version. I have also tried installing the bb version that has videos, #41 and there is a problem with this too on Samsung SM-T555 running on Android v6 (I was using a different device when we received Build #41 so I had not noticed this problem).
- I am able to install Build #41 on the tablet
- When I tap to open, it brings up a blank white screen that stays on for a few seconds, then the pop-up "Unfortunately HNQIS has stopped" appears.

**Comment by ifoche** [comment]
@cristinaelle just in case. Do you have any other DHIS app in the tablet that's not working? I mean EDS, MCS KH or MCS LA. If that's the case, can you uninstall it and HNQIS and try reinstalling HNQIS again? We experimented some incompatibility problems in the new SDK with other apps using also the SDK, so maybe the problem is there?

**Comment by rodmelia** [comment]
Android 6 support was addressed a long time ago.
