### ISSUE TITLE
Question parents and question parent options introduce "pull error during conversion" during metadata refresh

### ISSUE THREAD

**Issue by davidhuser** [EyeSeeTea/QAApp#184]
Not sure if it is configured correctly - example DE sheet here:
https://docs.google.com/spreadsheets/d/1ew0s-xIQVcwAhix_nqXQryXq87wmZ2GLMI0P2E1Uqg4/edit#gid=274658981&range=AC48

"38 Question Parents" tells which parent UID and column "39 Question Parent Options" is the option of the optionSet which was assigned to the parent (YES of optionSet "HNQIS - Yes1No0"). Do I misunderstand something here?

It crashes the metadata pull with "Error during pull conversion". App version 1.2.3

**Comment by ifoche** [comment]
Hi @davidhuser, can you send me testing server and credentials by email? In principle you're right. "39 Question Parent Options" tells which option expand the DE where you're configuring the behavior (the child question), while "38 Question Parents" actually says who is the parent of this question.

**Comment by ifoche** [comment]
@davidhuser the problem comes from a null pointer when accessing the parent question that's configured in the following child question (https://staging.psi-mis.org/api/dataElements/kwUBJw7Mdhb).  

Following the configuration of that DE, I think there's something wrong there. It is configured as parent question the following one (https://staging.psi-mis.org/api/dataElements/jWtk4JiNoF10), but if I try to access that DE using ifoche_hnqis it says "DataElement with id jWtk4JiNoF10 could not be found". So I would say either there's a typo in that UID, either ifoche_hnqis doesn't have permissions to see that DE.

Could you take a look to that DE? (jWtk4JiNoF10) and let me know what's wrong that avoids ifoche_hnqis from seeing it?

**Comment by davidhuser** [comment]
@ifoche - indeed it was a typo - if a UID ends with a number and that cell is drawn down (or up) it increases this trailing number rendering invalid UIDs (instead of copying that cell to the others). The Parent/Child logic works now. Thank you!
