### ISSUE TITLE
Download 12 month of surveys (rather than just 6)

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#196]
Hi @ifoche , health areas previously assessed are moving to "Never assessed" in the Plan Module. The same assessments also disappear from Improve Module. We have noted this for a number of countries e.g.  Kenya, Cambodia and Uganda. The data is at times in DHIS2, at times it is not. I have exported Uganda and Kenya databases to your email. Here are sample screenshots. 
![ug improve module](https://user-images.githubusercontent.com/26415203/30030907-ef3e831e-9197-11e7-8709-2187b12117e7.png)
![ug plan module](https://user-images.githubusercontent.com/26415203/30030908-f312bc30-9197-11e7-9e73-4f1bf87883a1.png)

**Comment by ifoche** [comment]
Hi @lindasato, the underlying reason for that is that initial pull is only taking into account surveys for the last 6 months. So if a program/ou has not been evaluated since more than 6 months, any new user that pulls data from the server won't get any survey for that program/ou and, hence, clasify it as never assessed. But it's just a matter of the amount of data that we're downloading from the server

**Comment by cristinaelle** [comment]
Do you think we can extend this to 12 months, please? 
Country teams are also saying that this hasn't happened for program/OU not evaluated in the last 6 months, but also for many others. Since we are asking them to update the app and refresh their metadata again for 1.2.8, it'd be nice if we could extend this to 12 months. I guess for this to be available we'll wait 1.3?

**Comment by rodmelia** [comment]
I agree that extending to 12 months is a very simple change that will address most of the cases.

**Comment by cristinaelle** [comment]
Guys - This is becoming more and more critical. Kenya, Nigeria and Cambodia are having issues with this. Rodolfo and I discussed whether it was possible to have this fixed in 1.2.X instead of waiting for 1.3 and I don't know what has been your final decision. Any news, please?

**Comment by rodmelia** [comment]
Cristina - Ignacio and I will reply to you shortly..

**Comment by cristinaelle** [comment]
I think this is related to #258, so I am closing this.
