### ISSUE TITLE
1.2.6 - No back arrow for videos

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#203]
When users watch videos, they have to use the device's back arrow if they want to go back and this takes them back to the Plan module. This is inconveniencing because when they manually go back to the Improve module, they have to start searching where they left off in the Improve module before they opened the video.
Can we have a go-back arrow when users watch videos that take them back to where they were in the Improve module? 

Ideally, we want to include this feature before the 1.2.7 release (or together?).

**Comment by ifoche** [comment]
Hi @cristinaelle , you're completely right. We'll review it

**Comment by rodmelia** [comment]
As discussed, this will be nice for 1.2.7, but not critical.

**Comment by ifoche** [comment]
What we've finally implemented in this part is to avoid the Android back button to take the user to the plan module. That's fixed, but we didn't introduce an specific back button in the interface.

**Comment by rodmelia** [comment]
That can certainly wait for 1.3 - thanks ignacio.

**Comment by rodmelia** [comment]
As reported by Ignacio, the simple implementation, i.e. Android Back button takes you back to the previous screen rather than the planning module, is already implemented for 1.3.0

WE WILL NOT implement the inclusion of a new button on the video UI - this will custom development and it is not justified.

I'm closing this issue.
