### ISSUE TITLE
Assess, Submission text box from the % Completion wheel

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#230]
Edit the text box: "Are you sure you want to mark this survey as complete? etc..."

![screen shot 2017-12-07 at 12 24 46 pm](https://user-images.githubusercontent.com/12784825/33707827-cb66126c-db49-11e7-9152-c80fbb69a344.jpg)

**Comment by rodmelia** [comment]
Rather than modifying the submit text box, we want to re-use the popup that we have on the listing screen, so we can show the wheel full size - see below (the logic for 'mark complete' of only being enabled when mandatory is 100%, as well as the confirmation pop-up should be the same as on the listing screen)
[Uploading Assess: Clicking on the wheel.png...]

**Comment by rodmelia** [comment]
uploading the pict again (having permission problems)
![Assess: Clicking on the wheel.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46c98789269190f3cfcab34aa756f99a2e06287d6910ab2e3092eb2dba4e394d4d1f0cf31b0d0c00eef39b2ea0e438708c0f0ded82645d74c23e11acb88016bc02b273995397f4edd4189fb5646fb2c99d452c1f0c1288fa5c36a19e4dce59f54ce44a47e9.png)

**Comment by rodmelia** [comment]
Please notice that the text is not final ! Cristina will give us final copy later.

**Comment by ifoche** [comment]
@cristinaelle, @rodmelia, can we consider that text as definitive?

**Comment by cristinaelle** [comment]
@purdych1 : please, check English language, tks!
