### ISSUE TITLE
Improve, feedback: - Indent feedback content

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#234]
Please, use different colors for the background of Questions and Feedback scripts. Maybe a different shade of grey? This will help users to distinguish between Questions and Feedback scripts more easily.

**Comment by rodmelia** [comment]
We will like to indent the feedback content - see sample below
![HNQIS - Indent feedback content.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46c0baab0ab1c3e4cfc0b147a153e4d42f4322772b05a0203086ec26ab4775154d435cec03070511afbd9b21b4b33a228e5c0dbed76d0c7dc43d15afb8821fbd08b923831c97aaaec81d9ebc6278bec1da0d2c14171980f55c30a19a48ca5df543e64451a3017b.png)

**Comment by ifoche** [comment]
Already implemented in 1.3

**Comment by cristinaelle** [comment]
It's not there in 1.3.

**Comment by ifoche** [comment]
@cristinaelle, maybe I'm wrong but I think this issue started with changing colors to distinguish feedback from the questions and later with Rodolfo proposal, that changed into creating the indentation to make it possible that differentiation. 1.3 is already creating the indentation, not the background color...so when you say that it's not done is because you would like to have also different background colors? Or is it something different?

**Comment by cristinaelle** [comment]
Ok, I am now seeing and indentation. Sorry for the confusion. Closing this.
