### ISSUE TITLE
Improve: Score color

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#24]
Feedback from gtsmith@psi.org : I cannot see this score - the color needs to be improved somehow. See comments

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d0a86bb9cf69010045b54c&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/c52d8498-ab62-43aa-87eb-c82942a5ed83.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>29% Unplugged</td></tr><tr><td>Memory free</td><td>245 MB / 1347 MB</td></tr></table>

**Comment by ifoche** [comment]
Related to #13. See explanation there

**Comment by gtrsmith** [comment]
I spoke with Rodolfo - we can try to use an alternation of grey colors for the background of the assessment listings so the score is more readable. Can we also make the score bold, if not already?

**Comment by ifoche** [comment]
I move it to "In progress" as I will darken the colors just to gain a little bit of contrast, but I talked with Rodolfo and I think this is something we will probably decide during the next week

**Comment by ifoche** [comment]
I set also the label question, to explicitly remark that there are things to decide here before the definitive solution is given

**Comment by cristinaelle** [comment]
The sorting order of the landing page of the Improve module is key, we have to discuss this more, and go for what makes most sense for the supervisors. Ideally, first we should sort all the facilities by date (first the facilities that have received a recent assessment) and then within each facility the sorting order of the assessments should be the same: first the assessments recently conducted. 
In this way the supervisor is able to see first the assessments he has just conducted at the facility where he is and provide feedback, and he also an overview of the last assessments conducted at that facility.

**Comment by cristinaelle** [comment]
A few things related to the layout of the Improve module (no screenshot attached because I'm at the airport and it's refreshing metadata and it's taking some time).
- In the actual Improve section of each assessment, when I want to provide feedback to the provider, the tablet reports the QoC score at the top of the page: make this much bigger, please,
- Each subsection reports a score: make the color of these scores consistent with our classes (<50%: red, <80%: yellow, <100%: green). At the moment there's an orange instead of yellow and I've seen that the color for scores less than 50% in not red, but it's orange,
- Can we make the header of each subsection bold, please? It helps the supervisor to differentiate between headers of subsections and actual questions to provide feedback on.

**Comment by gtrsmith** [comment]
@cristinaelle I am going to submit new buddybuild tickets for each of your three issues above. Otherwise, I will close this ticket because the original issue has been resolved
