### ISSUE TITLE
1.3 - Connect POEditor to 1.3 version

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#267]
Nice!! Minor comment: what is the plan for French, Portuguese, Laos and Khmer for this box? 

![3 assess](https://user-images.githubusercontent.com/12784825/38831799-30abfafc-41c9-11e8-9989-aff0a95b7b1c.png)

**Comment by rodmelia** [comment]
@ifoche  - Cristina tells me that she doesn't have access to PO editor - can we arrange access for her and Chris? (I'm assuming that these strings are in PO Editor)

**Comment by cristinaelle** [comment]
Make this text box available even if the inner circle doesn't reach 100%, so that users can tap on it and see the % of completion of both compulsory and all questions.

**Comment by ifoche** [comment]
Hi @rodmelia, I've just added Chris to the HNQIS project in POEditor (@ChrisR13 please let me know if you have any problem accessing it). @cristinaelle you are already among the translators.Can you check again if you can log in? Otherwise I can try removing you and adding you again, to see if it produces a new invitation

**Comment by ifoche** [comment]
BTW, these strings are not yet published in POEditor (it's still linked to the 1.2 version). Maybe we can use this issue to track the task of upgrading from 1.2 to 1.3 the terms in POEditor?

**Comment by cristinaelle** [comment]
Yes, I confirm I have access to the HNQIS Project in POEditor.
