### ISSUE TITLE
Completness colors

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#271]
How many colours/ ranges are:
1. Currently in use?
2. Can we use?
3. Can we have a different scale for the internal circle vs the external one?

**Comment by ifoche** [comment]
@rodmelia we're now using 3 ranges of color. Moving the thresholds is easy, changing the number of thresholds a bit more complicated. Current thresholds are:
- 80: low-to-medium threshold
- 90: medium-to-high threshold

Colors are different for the external and internal circles. Here their hexadecimal code.
For the external circle (non-mandatory):
- ratio_questions_high: 98fb98
- ratio_questions_middle: ffff00
- ratio_questions_low: ff0000

For the internal circle (mandatory):
- ratio_mandatory_questions_high: 0f7f12
- ratio_mandatory_questions_middle: fecb2f
- ratio_mandatory_questions_low: 890309

So I think I answered 1) and 2). For 3), it's exactly like regarding the number of ranges. Using the same ranges is quite quick, changing the scale to make them independent is not that quick. But of course, it can be done.

**Comment by cristinaelle** [comment]
Can we use the same thresholds and the same colors for both completeness scales?

- Below 80: low-to-medium threshold (ff0000)
- From 80 to 99: medium-to-high threshold (fecb2f)
- Above 99: high threshold (0f7f12)

**Comment by cristinaelle** [comment]
Yes, tks.

**Comment by cristinaelle** [comment]
Please, note that the color scales for completeness range are still different between all Qs and compulsory Qs. See below colors from the 2 wheels and the % of completeness:

![screen shot 2018-05-15 at 17 40 36](https://user-images.githubusercontent.com/12784825/40064648-a76e5288-5868-11e8-8b8c-15f367fb685e.png)

![screen shot 2018-05-15 at 17 40 47](https://user-images.githubusercontent.com/12784825/40064650-a79a3be6-5868-11e8-8faa-6575861cd4b4.png)

Is this because you think it'll be too confusing if we go for the same color scales for both completeness scores? I have noticed this when the 2 completeness scores match (see below): if we use the same color scales, the inner wheel will not be visible.

![screen shot 2018-05-15 at 17 42 31](https://user-images.githubusercontent.com/12784825/40064636-9f8d607c-5868-11e8-9a17-3988b02ebd77.png)

**Comment by cristinaelle** [comment]
![screen shot 2018-06-11 at 16 03 28](https://user-images.githubusercontent.com/12784825/41233101-044a594c-6d91-11e8-91b0-65b79a8a45b9.png)

The color scales look good because they use 2 different shades of green - yellow - red for the inner and outer circles, so users can distinguish the 2 circles even when the % of completion are similar for the two sets of questions (compulsory and all). No need to change anything in terms of colors.

The only thing to do is to change the cutoffs as above, so that we have the green to appear just when it's above 99%:

Below 80: low-to-medium threshold 
From 80 to 99: medium-to-high threshold
Above 99: high threshold
