### ISSUE TITLE
1.3 - Improve: provider's name reported in the Obs & Action Plan below the first level of the HNQIS checklist

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#281]
We are working to introduce for all Health Areas the possibility for supervisors to collect provider's name, age and gender. In the Assess module, we'll have 3 new DEs (provider's name, age and gender) **at the top of each tab** (i.e. for FP we have 3 tabs: Oral Contraceptives, IUDs, Injectables. Supervisors will collect provider's name, age and gender 3 times, once for every tab). 
We want provider's name to be reported in the Obs & Action Plan both in the simple and formatted text. The provider's name will appear below the row that shows the score of the tab for every tab. 

Simple text (1 tab as an example):

![picture1](https://user-images.githubusercontent.com/12784825/39532332-517180b8-4e35-11e8-95c0-16092dc14fa0.png)

Formatted text (2 tabs as an example):

![picture1](https://user-images.githubusercontent.com/12784825/39532632-ddb79f62-4e35-11e8-98f4-db8e18c3cf2f.png)

**Comment by ifoche** [comment]
@cristinaelle in 1.3 there's no longer a formatted text sharing (unless we're talking about the URL that's shared via the simple sharing). Is this a 1.3 or a 1.2 issue?

Moving the place where the provider's name is in the shared text is quite simple, but I think you're meaning introducing a per-tab provider data element that would be recognized and introduced on top of each "section" of the feedback. This is particularly difficult because feedback is based on composite scores, that are hierarchical and not necessarily attached to the per-tab distribution. In theory, you can have data elements belonging to one section (CS) that is mostly contained in one tab, but with also data elements in other tabs...so how to decide which provider name goes where? We could maybe think on adding the provider's name question to the specific composite score, but definitively IMHO it is not something very simple to include in a maintenance release...but in a full release. I hope it makes sense. What do you think?

**Comment by cristinaelle** [comment]
Right - I am referring to the url shared via the simple text. 

Let us think through your second Q a bit more and will come back to you with an answer. This is a critical piece according to what we are hearing from countries, so we need to find a solution. We can add to every single HNQIS checklist a first tab that is Provider's details that reports Provider's name, sex, age, education level, etc. In case supervisors assess more than one provider during a supervision visit, they will complete more HNQIS assessments. If we go for this, in the Obs & Action Plan, you will report Provider's name before the QoC score. This might be the simplest option.

**Comment by ifoche** [comment]
Ok, so for the first question about the URL, I defer to @rodmelia. We're don't manage the web part.

For the second thing, I think is doable, to add a provider name DE to a composite score. Probably it's just a matter of grouping this with #263, and maybe another feature and creating a 1.4 with them...but obviously that's something that you have to decide. Just let me know whenever you have a decision on how you prefer to deal with this.

**Comment by cristinaelle** [comment]
yes, we have emailed country teams to let us know what they prefer between (i) provider's details per checklist (as you suggested, and this is my preferred option, too) and (ii) provider's details per tab. Will let you know asap.
