### ISSUE TITLE
Add server URL query string parameter

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#288]
Add server URL parameter so it becomes available for all servers - including sfhnigeria and singapore servers

**Comment by ifoche** [comment]
@rodmelia how would the user change that parameter? a setting I guess? Would that setting be hidden under developers options?

**Comment by ifoche** [comment]
Maybe we could pass the same server we're connected to and the user cannot change it without changing the server? Does that make sense?

**Comment by rodmelia** [comment]
Yes - that's all we need to pass: the URL used for the initial connection.

**Comment by cristinaelle** [comment]
1.3.4: the url doesn't work on sfhnigeria and singapore-dev servers.

![screen shot 2018-07-23 at 12 15 08](https://user-images.githubusercontent.com/12784825/43082166-134c1b16-8e9c-11e8-887b-453a15ac0694.png)

Also, the url doesn't report Gaps and Action Plan. These fields are blank. 

![screen shot 2018-07-20 at 15 15 40](https://user-images.githubusercontent.com/12784825/43082182-1dc5707e-8e9c-11e8-98c1-b89365176c63.png)

**Comment by rodmelia** [comment]
we are missing the necessary user on those servers - i will provide details soon for creating those users.

**Comment by lindasato** [comment]
@ifoche ,
1.3.5: the url is now working for the sfhnigeria server but it is not available for the singapore-dev server.

**Comment by cristinaelle** [comment]
@rodmelia : please, take care of this for the version Ignacio will publish on Sep 7.

**Comment by rodmelia** [comment]
assigned to tran - I've cc'ed crisitna and janet in the email.

**Comment by rodmelia** [comment]
update @ifoche  - Janet reports that for Singapore-dev the URL doesn't get generated by the app - see screenshot. Needs investigation (let's test in our call tomorrow)
![Screenshot_20180830-120528[1].png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56b36ea0c587de1300b8b565/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791e74236455f17b25d7bb13ee7f394d4d1f0cf31b0d0c00eef39b2ea0e438708c0f0ded82645d74c23e11acb88016bc02b273995397f4edd4189fb5646fb2c99d452c1f021288fa5e30a69a49c95af54fe94447e9.png)

**Comment by rodmelia** [comment]
When a survey has not been sent to the server, it is not possible to generate a URL for web feedback, as the UID event assignment is pending. Hence the message.

We should display a better message - see #303

**Comment by cristinaelle** [comment]
Reopening this issue because the url generated from surveys sent to the server https://clone-zw.hnqis.org does not work correctly. The url is generated (meaning there is an event id in the server), but then the url doesn't work. Error message: Failed to authenticate in server https://clone-zw.hnqis.org

Try with this link:

https://apps.psi-mis.org/hnqis/feedback?eventId=tpgKEiA37i6&server=https://clone-zw.hnqis.org

![screen shot 2019-01-11 at 11 16 45](https://user-images.githubusercontent.com/12784825/51021371-69720780-1592-11e9-9626-921895c2da66.png)

**Comment by ifoche** [comment]
I defer this to @rodmelia as it has to do with the WS

**Comment by cristinaelle** [comment]
@rodmelia: what is the plan for this? Also, note the url generated has a dash at the end of the server URL and this leads to a blank page. See examples below for

(i) clone-zw.hnqis.org not working: https://apps.psi-mis.org/hnqis/feedback?eventId=tpgKEiA37i6&server=https://clone-zw.hnqis.org
(ii) url generated in the Obs & Action Plan with a slash at the end: https://apps.psi-mis.org/hnqis/feedback?eventId=njrFGg8OBq2&server=https://data.psi-mis.org/

thanks!

cristina

**Comment by cristinaelle** [comment]
I have set up the hnqis.webapp user on the following servers:
- ao-dev.hnqis.org
- im-dev.psi-mis.org
- myanmar.psi-mis.org
- sfhza.psi-mis.org
- sm-dev.hnqis.org
- zw.hnqis.org

Tonight, I will update the pw on data and clone servers, as well, and Tran will update the pw in the apps website, as well. 

Please, @lindasato: try whether this is working or not from tomorrow onwards (Thu, Nov 21st) (when you have a second).

Thanks, 

cristina

**Comment by lindasato** [comment]
Hi @cristinaelle , all the urls are leading to the surveys except for ao-dev.hnqis.org which has a bug preventing sharing of the action plan and I am therefore unable to test this. I will confirm this once ticket #331 has been resolved. Other issues to note:
-sm-dev.hnqis.org: the assessments are duplicated. Esunly had already raised a ticket here for this.
-myanmar.psi-mis.org: the checklists are in Burmese and this is reflecting as question marks in the survey. I have checked Laos (which is on data server) and the questions appear as question marks too. Should I raise a ticket for this to be fixed in 1.5?

![Myanmar Surveys](https://user-images.githubusercontent.com/26415203/69239705-e7883d00-0bab-11ea-9e6a-de31734c506a.PNG)

**Comment by cristinaelle** [comment]
@lindasato : thanks for testing this so quickly! I am closing this ticket because it seems that this works well, apart from the issues already raised in other tickets. for Burmese and Lao language, yes, let's raise another ticket and assign this to @rodmelia because I guess it's something to do with the web page and rendering in alphabets others than latin.
