### ISSUE TITLE
1.3.4 - Improve: sharing Action Plan

### ISSUE THREAD

**Issue by cristinaelle** [EyeSeeTea/QAApp#298]
On most Android devices, when the user shares an Action plan, he is asked to choose a messaging application (i.e. WApp, skype, sms, etc) and he is also asked to choose to use the selected app 'Just once' or 'Always'. It has happened that a user has selected 'Always' for a wrong app and can't revert his choice. Is there a way to avoid that message to pop up and have HNQIS to ALWAYS ask the user which messaging app he wants to use to share the Action plan?

**Comment by ChrisR13** [comment]
Hi all - I tested a different aspect of the issue and received the same result. I completed the action plan and selected OneDrive as the app. Before completing, I hit return to remove me from the OneDrive app and return me to improve. When I tried to hit the send button again, I noticed that it automatically took me to OneDrive instead of taking me to the other app options.

**Comment by rodmelia** [comment]
if you go to: Settings--->Apps-->HNQIS-->Reset App Preferences, this will force the app to ask again. We could investigate if we can prevent the app remembering - this is controlled by android.

**Comment by cristinaelle** [comment]
On some Android devices, the only option is Factory Data reset and this resets the phone and erases all data including files that have been downloaded (all messages and photos, etc). Let us know how much it costs to have HNQIS preventing to remember the option selected. This will be our preferred choice. Thanks.

**Comment by rodmelia** [comment]
@ifoche - can you force android NOT to remember programatically?

**Comment by ifoche** [comment]
@rodmelia that's an Android control. As far as I know we cannot do it by using the default behavior. But we could investigate a bit other solutions. The most evident one is to re-design the screen that ask for the app selection, and ask for a subgroup of apps that we would open in an explicit way instead of an implicit one. But this is not very quick to implement. Would that work?

**Comment by cristinaelle** [comment]
Thanks for looking into this. Consider how low priority this is, let's drop this and move this to the backlog of nice-to-have features to implement when we raise more money.
