### ISSUE TITLE
Better message for case 'URL not yet availalbe'

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/QAApp#303]
When a survey has not been sent to the server, it is not possible to generate a URL for web feedback, as the UID event assignment is pending. We should display a better message -

Proposal: 'Survey not yet synchronized with server - feedback URL not yet available'

**Comment by rodmelia** [comment]
@ifoche - before implementing, we need approval of the message from the HNQIS team

**Comment by cristinaelle** [comment]
'The feedback URL is not available because the survey hasn't been sent to the server yet. Try sharing the feedback again later.'

**Comment by cristinaelle** [comment]
Please, release a 1.4 candidate in time for the upgrade to 2.30 with a better message in case the URL is not available because the event id hasn't been created yet. The current version 1.4 still shows 'URL not yet available'.

![screen shot 2019-01-11 at 09 46 24](https://user-images.githubusercontent.com/12784825/51017654-d16e2100-1585-11e9-80c5-99c7834f6787.png)

**Comment by ifoche** [comment]
Taking care of this
