### ISSUE TITLE
1.5.0 - No action plans in monitor module

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#323]
We can see incomplete and complete menus but this module isn't populated with action plans, so we are unable to test it
![Monitor menus blank](https://user-images.githubusercontent.com/26415203/61725081-cc313080-ad77-11e9-9373-0ba921fc3c5a.jpg)

**Comment by ifoche** [comment]
Hi @lindasato . I can see in your screenshot that you're filtering by health area. You probably don't have any complete/incomplete because in order to have it you need to start an observation and action plan, so you have 3 actions that can be in a complete or incomplete state. As you're filtering, if you don't have an obs & action plan started for that health area, it might be normal that you don't have anything there. Can you check that?

**Comment by lindasato** [comment]
Hi @ifoche we tested this after completing action plans. I have just retested it, I am even able to email the action plan but the action plan is not getting picked up in monitor module.
