### ISSUE TITLE
1.5.0 - Competency Classes not working correctly

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#325]
The competency classes are not working correctly as per the description in the tech specs document. (see below)
**Rate providers as competent, competent but needs improvement or not competent
- All critical steps and ≥ 90% non critical steps correct = Competent
- All critical steps correct and between 80% and < 90% non-critical steps correct = Competent but needs improvement
- Any critical step missed and below 80% of non-critical steps correct = Not competent**

The critical questions are behaving fine, the issue is with the non-critical questions 
(i) The non-critical questions are not not being factored as per the cut-offs above
(ii) The competency class is factoring in non-critical questions which are not answered (skipped) and this shouldn't be the case.

Here are some scenarios we encountered while testing
[1.5.0_Competency classes scenarios.xlsx](https://github.com/EyeSeeTea/QAApp/files/3431650/1.5.0_Competency.classes.scenarios.xlsx)

**Comment by nancyespinoza** [comment]
**1.5.3**
We tested the cases documented in the spreadsheet attached by Linda. Only two of the cases are NOT working as expected:

**1. All critical steps are correct and NONE of the non-critical steps have answer**
(Row 12 in spreadsheet) The expected behavior would be to hide the competency class or "add" a "not applicable NA" status. @cristinaelle to confirm.

**2. All critical steps are correct and 80% of non-critical steps are correct **
The expected behavior would be to classify this as a _Competent but needs improvement_ but the app is rendering _Not Competent_.

**Comment by cristinaelle** [comment]
hi @nancyespinoza: correct, the plan is to have at least one compulsory question, so this needs to be taken care of during the program configuration process.

**Comment by ifoche** [comment]
Hi @nancyespinoza . Thank you for the testing efforts. Could you please send me by email an example we could replicate? I'm thinking on user:pass@server you used and the example survey, so we can have exactly the same situation. 

Thank you!

**Comment by nancyespinoza** [comment]
Hi @ifoche. After discussing this with @cristinaelle, the following adjustmen is needed in the competency score:
All critical steps and (≥ 89.9% non-critical steps correct OR NONE OF THE NON-CRITICAL STEPS ANSWERED) = **Competent**
All critical steps correct and between 79.9% and < 89.9% non-critical steps correct = **Competent but needs improvement**
Any critical step missed and below 79.9% of non-critical steps correct = **Not competent**

Let me know if everything is clear. Thank you.

**Comment by ifoche** [comment]
thank you, @nancyespinoza I think it's clear.

**Comment by anamariaelsal** [comment]
Hello @ifoche , this is Ana Maria, part of the testing team.  About the 1.5.4 testing and in regards of this particular bug, please take note the issue is still present, for those cases were all the critical questions have been correctly answered and none of the non critical have been answered, the App still renders the Class as Non Competent.  You can use the same spreadsheet that Nancy and Linda used to report this case before.  Please do let me know if need further information.  Thanks!
