### ISSUE TITLE
1.4.6- Partial logos on sm-dev.hnqis.org and im-dev.psi-mis.org servers

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#334]
The logos on sm-dev.hnqis.org and im-dev.psi-mis.org servers are partially cut out. All we can see is a "2". See image below.

![SM server logo](https://user-images.githubusercontent.com/26415203/67800839-13c30900-fa99-11e9-94ff-f667dce3ec20.jpg)

**Comment by ifoche** [comment]
Dear @lindasato , the app's getting from the server the DHIS2 logo, which happens to be transparent background + DHIS2 letters in white. That's why you cannot see the rest of the logo. My suggestions to solve this issue would be:
1) To change the logo in the server, so it's not the old DHIS2 one, or at least not with a transparent background
2) For us to change the app's background color of the header, so DHIS2 white letter contrasts with the background color and you can read the DHIS2

What do you think is best?

**Comment by lindasato** [comment]
Thanks for the response Ignacio. I will let @cristinaelle make the decision on this.

**Comment by cristinaelle** [comment]
hi @ifoche: thanks for this explanation. Considering that we have the same issue with im-dev.psi-mis.org and also in the server the logo doesn't look nice, I think it's ok to change the logo in the server itself, so that we also fix the way the logo looks server-side.

@lindasato: I can work on it at some point this / next week.

![image](https://user-images.githubusercontent.com/12784825/67942493-ff8e2180-fbe8-11e9-928b-1868cdba96ee.png)
