### ISSUE TITLE
1.5.1 -Competency class displaying as Not Available

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#343]
I have an assessment I conducted 2 days ago that has a score of 80% and the class should be **Not Competent** but it is displaying as Not Available. Not sure why it is **Not Available** 

![Competenct class NA](https://user-images.githubusercontent.com/26415203/68016771-4e4dc100-fca6-11e9-8762-917d6869242d.jpg)

**Comment by ifoche** [comment]
Hi @lindasato could you please provide the DB? We cannot replicate it and we would like to investigate a bit more to check whether there's something that we can do to reproduce it. There's a checkbox that allows you to show only the last assessment or all of them...could you ensure that you're representing the last assessment and not showing a previous one? I'm sure it's not the issue, but just to discard any possibilities

**Comment by lindasato** [comment]
Hi Ignacio. I had already sent this db from my gmail account (lsatokili@gmail.com)

**Comment by ifoche** [comment]
thanks!

**Comment by ifoche** [comment]
Dear @lindasato,

as per our investigation on this, we think that the survey that's showing not available has been created using 1.4.x HNQIS and then a login using 1.5.x can only represent NA, because the competency value was not sent. It's a normal situation when, e.g., 2 testers are sharing the same user for testing 1.4.x and 1.5.x at the same time using the same server. Please check the event here:
https://clone.psi-mis.org/api/events/JdKPmyllSAX

You will see that there's no value for competency there:
https://clone.psi-mis.org/api/dataElements/KesgQ5NHkQW (_Overall Competency)

That would be a demonstration that it was sent by using 1.4.x

Does it make sense for you?

**Comment by lindasato** [comment]
Hi @ifoche , okay. Makes sense.
