### ISSUE TITLE
1.4.2 and 1.5.1 - Incorrect "Due Date" in mass reschedule

### ISSUE THREAD

**Issue by lindasato** [EyeSeeTea/QAApp#344]
The due date in the reschedule feature of plan module is not correctly reflecting the date the assessment was completed/created. See sample screenshots from 1.4.2 below where the dates are correct in improve module but the due dates in reschedule feature are different. The same is happening in 1.5.1. The due date is picking the date when you log into the app or refresh metadata.

![Due date bug](https://user-images.githubusercontent.com/26415203/68187809-ae9b7600-ffb8-11e9-8d9f-ff876e9cbc8e.PNG)

**Comment by ifoche** [comment]
Hi @lindasato , 

Actually, the app's looking at the creation date of the planned survey, which is not something that has been recovered from the server, but created by the app itself. That's why it changes with the login. 

We could look for the completion date of the previous survey for that OU/program and use that date if you think it's correct. In that case, would it be ok to use "Last comp. date" as the title for that column that now is called "due date"?

**Comment by lindasato** [comment]
Hi @ifoche ,suggesting "**Comp date**" which is the term used in improve module. Alternatively, you can name it "**Last QA**" then rename "Scheduled" to "**Next QA**" (Next QA is used in the landing page of plan module).

**Comment by ifoche** [comment]
ok, thanks!
