### ISSUE TITLE
Not able to mark complete

### ISSUE THREAD

**Issue by esunly** [EyeSeeTea/QAApp#348]
Hi @ifoche,

I'm having a really weird issue. Maybe I'm doing something wrong or there is any config problem causing the issue but I haven't been able to figure this out.

I managed to mark a survey as completed several times but noticed that one of the headings did not have the icon to allow me to display the content (even though that section had been answered). See the attached "Improve" screenshot.

Then I tried to complete only that particular tab to test (in the other tabs there are compulsory questions but remained hidden under a parent question, which I did not answer) but could not mark as complete. I reviewed several times to see if I was missing any compulsory question but could not find any. 

Do you have any idea of what might be causing this behaviour? Can you please help me troubleshoot? This is in the https://sm-dev.hnqis.org/ server, survey PL HNQIS Maternal and Newborn Health and tab Antenatal Care (ANC)

Many thanks,
Esunly

<img width="553" alt="Improve" src="https://user-images.githubusercontent.com/8968736/69051152-ce448c80-0a03-11ea-9320-f5744d3b1fca.png">

**Comment by ifoche** [comment]
Hi @esunly, 

we couldn't test exactly with the same survey/user, but using another one in the same server, what we discover is that at least in our case, the only situations where you don't get the deploy arrow (and hence you cannot show the answers for a composite score) is when you didn't answer to any question. Could it be your case, too? Are you sure that you answered to all the questions? Otherwise, could you share the DB with me so we can have a look?

Thanks!

**Comment by esunly** [comment]
@ifoche 

Sorry for my delayed response! The issue seem to be resolved by now. If this happens again I'll open a new issue. You can close this one.

Thanks,
Esunly
