### ISSUE TITLE
1.5.4 - Change label of  Monitor Module

### ISSUE THREAD

**Issue by anamariaelsal** [EyeSeeTea/QAApp#358]
Currently, the label of the Scores Chart Dashboard in the Monitor Module is stated as Quality of Care.  
It has been requested to change it to: "Competency class" , to be aligned with the new classification schema.
Please take a look of the area where the change is required

![Monitor_module_label](https://user-images.githubusercontent.com/29080974/80425696-6a22d000-88a1-11ea-9c0b-7ec1c5ce2597.png)

**Comment by cristinaelle** [comment]
We have also noticed that the label reports 'Last 6 months' when it's actually Last 5 months + Current month. Since you are changing the label, I suggest changing it to 'Competency Classes - 6 months'.

**Comment by cristinaelle** [comment]
I have also just noticed that we might want to lose A / B / C next to (C) / (CNI) / (NC). Not sure why we have A / B / C in this version, considering the Quality of care classes are nowhere. I know this trick might come in hands for 1.6 (still TBC); however, in 1.6, also, we might want to have either A / B / C or C / CNI / NC and not both because it really confuses users, above all when they'll transition from QoC scores to Competency classes.

![image](https://user-images.githubusercontent.com/12784825/82812664-2caf6380-9e9c-11ea-97c6-bfdc1164adef.png)
