### ISSUE TITLE
error message when required authority is not present

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#369]
error message when trying to login when the user does not have the authority "F_IGNORE_TRACKER_REQUIRED_VALUE_VALIDATION"

**Comment by ifoche** [comment]
@nancyespinoza what should we do with current logged users? Shall we logout them if they don't have the authority? Shall we show a dialog reading "You don't have a required authority, please contact your administrator" or something like that?

**Comment by nancyespinoza** [comment]
I think a pop-up message should work  ("You don't have a required authority, please contact your administrator" looks good to me). @rodmelia what do you think?

**Comment by rodmelia** [comment]
Final implementation
- at login
- just before sending survey

"You don't have HNQIS user role - please contact your administrator"

**Comment by rodmelia** [comment]
No need to log-off the user

**Comment by nancyespinoza** [comment]
### **A. Error message at login- Fail**
The message is showing but the problem is that if you logout or cancel the login and then you change the server (same user) the app keeps showing the message. The reverse is also happening, meaning that if I log in with a user that have the role, log out, and then login with a user that does not have the role, the app let me login but shows the message when I try to send a new survey. 

Steps to replicate
1. Try to login with the following credentials: server (https://staging.psi-mis.org), user(KEdemo1), password (Kenyademo1!)
2. You should not be able to log in.
3. Change server to https://data.psi-mis.org
4. You should be able to log in but the app keeps showing the message.

CASE 2
1. Login with the following credentials: server (https://data.psi-mis.org), user(KEdemo1), password (Kenyademo1!)
2. You should be able to log in
3. Log out
4. Login with the following credentials: server (https://staging.psi-mis.org), user(KEdemo1), password (Kenyademo1!)
5. Tou should not be able to log in, the app let you but once you try to send a survey, an error message pops-up.

Video example: https://drive.google.com/file/d/1y7vYHLXeI0-VConNOBteyNyVEDDmgG0I/view?usp=sharing

### **B. Error message before sending survey- Pass**

**Comment by ifoche** [comment]
Was implemented in the latest release
