### ISSUE TITLE
Error message when installing an APK

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/QAApp#370]
We have notice that if we install a new APK without uninstalling the previous app, the new app crashes a lot. I'm assuming this is not a bug but to avoid these type of errors, is it possible to add an error message not allowing the user to install the APK until the old one is uninstalled?

**Comment by ifoche** [comment]
Hi @nancyespinoza . If the app's crashing when you install a new version, that's perfectly a bug. There are migrations of the DB between one version and the next one, and theoretically they should have been automatically managed by the app. In order to properly replicate this issue...would you  know which version you were coming from and which new version you were installing?

If you could also describe more or less where the app was crashing, that could also provide some precious information.

Thanks in advance

**Comment by rodmelia** [comment]
@nancyespinoza  - could you please confirm that the issue is:
1.4.7 --> 1.6.X

Ignacio - start working on this, even if Nancy doesn't reply

**Comment by rodmelia** [comment]
@nancyespinoza - could you confirm where are the crashes happening?

**Comment by nancyespinoza** [comment]
Hi @ifoche the crash happened from 1.6.2 (dev) to 1.6.3 (dev)

Steps to replicate:
1. Install 1.6.2
2. Without unistalling the previous apk, install 1.6.3
3. Open the new app, and login (KEdemo1, Kenyademo1! for example). After clicking the "log in" button, the app crashes.

**Comment by ifoche** [comment]
@nancyespinoza could you please let us know which device and exact OS are you using for this test?

Thanks in advance

**Comment by ifoche** [comment]
@nancyespinoza we're not able to reproduce this error from 1.6.2 to 1.6.3. The problem is, however, from 1.4.7 to 1.6.3 perfectly replicable, so we've fixed that one. Please if there's anything else that could give us any clue to understand the other use case, we will really appreciate it.
