### ISSUE TITLE
Monitoring Section: Assessments with QoC score in class A are not reflected in monitoring table

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#4]
Feedback from clussiana@psi.org : Assessments with QoC score in class A are not reflected in the table.

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56d06d77bacc2f0100836f30&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d057fac8f4aa010054eac5/54c88e54-eed7-4e54-9b33-f68edbff7560.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>62% Unplugged</td></tr><tr><td>Memory free</td><td>287 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
@cristinaelle the upper chart is showing the total amount of each class that have been sent to the system, while the table down is showing you the average score for each month. So I think that those A classed surveys are present, but the average of the month in which they were sent is not class A.

**Comment by cristinaelle** [comment]
Trying to interpret this: the doughnut is clear, the table is confusing to me, can you please check whether the table reports average scores, please?
I've sent an assessment on ANC, the QoC score was Class A. It's not reflected in the table, though, because at the moment the table doesn't include March within the last 6 months. 
Can you check, please, if that score is reported in the table under March? Thanks!

![screen shot 2016-03-01 at 5 21 01 am](https://cloud.githubusercontent.com/assets/12784825/13415672/b36782ce-df6d-11e5-8109-437c29683d7a.jpg)

**Comment by ifoche** [comment]
I think that you tested in a very special day. 29 of February, just moving to march, with a server that probably is in Europe and I don't know where you tested from...can you please test it again today and tell me if you still don't have march in your table please? You should be getting a March column with the average score of every survey that you uploaded in march.

**Comment by cristinaelle** [comment]
Done it and still not working. There's a new thread on this because I've sent a new screenshot on this.

**Comment by ifoche** [comment]
Ok, just to continue the discussion about it in this thread, I put a reference to the new issue you created (#40)

**Comment by ifoche** [comment]
And just in case, this is also the same issue as #6

**Comment by gtrsmith** [comment]
@cristinaelle, the table is actually showing the average for March, which I dont think we should change necessarily. If we show ever score on this table, it could become too long and would not look as good. I am going to mark this for consideration in H15

**Comment by cristinaelle** [comment]
@gtrsmith: I meant that the average is not taking into account the scores I was getting when submitting empty assessments (0% = Class C). I'm fine with the system reporting the average, only, but at that time it was not including the assessments I was submitting. 
Ignacio told me this was because there was an issue with the dates and it has now been resolved.
To close this, I guess.

**Comment by rodmelia** [comment]
I think it is time to close this one...
