### ISSUE TITLE
Is it possible to rearrange this in order of facility?…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#53]
Feedback from clussiana@psi.org : Is it possible to rearrange this in order of facility? During the demo in Cambodia, they've also asked if it's possible to have in in the upper part of the screen the assessments recently conducted, so that they can easily find the ones they have to give a feedback on.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56db0401878a7e01002c67ad&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/2f93c7fe-3ff7-42c2-bfc7-fbf58a4a6a70.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>95% Unplugged</td></tr><tr><td>Memory free</td><td>373 MB / 1376 MB</td></tr></table>

**Comment by cristinaelle** [comment]
Sometimes the Improve module reports facilities duplicated, other times it doesn't.
Can we work on the following sorting order, please? The **first** sorting order should be by facility and the first facility is the one that has received the most recent assessment. The second facility is the one for which the last assessment is older than the last assessment of the first facility, etc.
Then, we have a **second** sorting order, within each facility: and this is by date of assessment, so that for each facility we have first the most recent assessments and then the others.
In this way, when a supervisor conducts an assessment and moves to the Improve module, he first see the facility where he's at and then the assessment he's just conducted. And he'll also be able to have an overview of the QoC score from all the other health areas for that facility. Is this clear?

**Comment by rodmelia** [comment]
WIth H14 build 7, we no longer have 'All Org Units', so you always get a very concise list of assessment for that Org Unit. Things that we can do:
1. By default , most recent assessment at the top
2. Org Unit Selector defaults to the last Org Unit assessed
You can still click on the column headers, and reorganize by Survey Name / Date / Score

**Comment by cristinaelle** [comment]
I'll go for most recent assessments at the top and I'll keep both the drop-down menus, Assessments and Facilities (let's change this from Org Units to Facilities).

**Comment by cristinaelle** [comment]
This has been address in 1.3. Closing.
