### ISSUE TITLE
Sum of num and den doesn't update.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/QAApp#57]
Feedback from clussiana@psi.org : The score of num and den doesn't update.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56b408ad65c5670100adf4df/feedback?fid=56dbb3c52f5f410100440e78&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56b408ad65c5670100adf4df/56d774842ebeba010067f8b1/1779b7fe-9186-47a5-a245-f9348f310d6f.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T531</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>61% Unplugged</td></tr><tr><td>Memory free</td><td>287 MB / 1376 MB</td></tr></table>

**Comment by ifoche** [comment]
The truth is that we have num/dems quite forgotten. We haven't been paying attention to them since some releases ago. Is it something we want to keep? s it something that is disappearing?

**Comment by cristinaelle** [comment]
I think we should keep them, yes. The supervisors have not been involved at all in the scoring system of these checklists, so they don't know how the provider ends up with a QoC score. We should keep them, so that the supervisor can see how well the provider is performing during the Assessment phase and see what are the steps that have more weight compared to others. 
If we don't keep them, there's the risk that the supervisors don't know how to explain to the providers how they've ended up with the QoC score they've got.

**Comment by ifoche** [comment]
We're going to remove the summary bar and move the settings option to the bottom

**Comment by cristinaelle** [comment]
:)

**Comment by gtrsmith** [comment]
This is resolved
